= emf2svg

== Purpose

Provides Ruby access to https://github.com/kakwa/libemf2svg (temporarily using
the https://github.com/metanorma/libemf2svg[Metanorma fork] until upstreaming
is complete).

== Installation

Install the gem directly:

[source,sh]
----
gem install 'emf2svg'
----

Or add it to your `Gemfile`:

[source,ruby]
----
gem 'emf2svg'
----

== Usage

This gem embeds libemf2svg, allowing your Ruby code to utilize EMF to SVG
conversion facilities.

TODO.

== Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run
`rake spec` to run the tests. You can also run `bin/console` for an interactive
prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`. To
release a new version, update the version number in `version.rb`, and then run
`bundle exec rake release`, which will create a git tag for the version, push
git commits and the created tag, and push the `.gem` file to
https://rubygems.org[rubygems.org].

== Contributing

Bug reports and pull requests are welcome on GitHub at
https://github.com/metanorma/emf2svg-ruby. This project is intended to be a
safe, welcoming space for collaboration, and contributors are expected to adhere
to the
https://github.com/metanorma/emf2svg-ruby/blob/master/CODE_OF_CONDUCT.md[code of conduct].

== Code of Conduct

Everyone interacting in the emf2svg project's codebases, issue trackers, chat
rooms and mailing lists is expected to follow the
https://github.com/metanorma/emf2svg-ruby/blob/master/CODE_OF_CONDUCT.md[code of conduct].
