#!/usr/bin/env ruby
# frozen_string_literal: true

require "emf2svg"

def print_usage
  usage = %{
    Usage: emf2svg <input> <output>
        <input>  -- emf file to convert
        <output> -- svg file to save
    }
  puts usage
end

if ARGV.size != 2 || ARGV[0].casecmp("help").zero?
  print_usage
  exit 0
end

begin
  svg = Emf2svg.from_file(ARGV[0])
  File.write(ARGV[1], svg, mode: "wb")
rescue StandardError => e
  puts "Failed to process #{ARGV[0]}: #{e.message}"
  print_usage
end
