name: main

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true

    - run: bundle exec rake

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
            platform: any
          - os: ubuntu-18.04
            platform: x86_64-linux
          - os: ubuntu-18.04
            platform: aarch64-linux
          - os: windows-latest
            platform: x64-mingw32
          - os: macos-latest
            platform: x86_64-darwin
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - run: bundle exec rake gem:native:${{ matrix.platform }}

      - uses: actions/upload-artifact@v2
        with:
          name: pkg
          path: pkg/*.gem

      - name: Install gem
        run: gem install --no-document pkg/emf2svg-*.gem

      - name: Test conversion
        run: |
          ruby -remf2svg -e "puts File.write('output.svg', Emf2svg.from_file('spec/examples/image1.emf'), mode: 'wb')"

  test-build:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: any
          - os: windows-latest
            platform: any
          - os: macos-latest
            platform: any
          - os: ubuntu-18.04
            platform: x86_64-linux
          - os: ubuntu-18.04
            platform: aarch64-linux
          - os: ubuntu-latest
            platform: x86_64-linux
          - os: ubuntu-latest
            platform: aarch64-linux
          - os: windows-latest
            platform: x64-mingw32
          - os: macos-latest
            platform: x86_64-darwin
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - uses: actions/download-artifact@v2
        with:
          name: pkg
          path: pkg

      - name: Install native gem
        if: matrix.platform == 'any'
        run: gem install --no-document pkg/emf2svg-$(ruby -I lib -r emf2svg/version -e "puts Emf2svg::VERSION").gem

      - name: Install binary gem
        if: matrix.platform != 'any'
        run: gem install --no-document pkg/emf2svg-*-${{ matrix.platform }}.gem

      - name: Test conversion
        run: |
          ruby -remf2svg -e "puts File.write('output.svg', Emf2svg.from_file('spec/examples/image1.emf'), mode: 'wb')"
