name: main

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6
        bundler-cache: true

    - run: bundle exec rake

  build-gem:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - run: bundle config set path 'vendor/bundle'

      - run: bundle install --jobs 4 --retry 3

      - run: bundle exec rake build

      - uses: actions/upload-artifact@v2
        with:
          name: pkg
          path: pkg/*.gem

  test-gem:
    needs: build-gem
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: pkg
          path: pkg

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Install gem
        run: gem install --no-document pkg/emf2svg-*.gem

      - name: Test conversion
        run: |
          ruby -remf2svg -e "puts File.write('output.svg', Emf2svg.from_file('spec/examples/image1.emf'), mode: 'wb')"
