name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
            platform: any
            ruby-version: '2.7'
          - os: ubuntu-18.04
            platform: x86_64-linux
            ruby-version: '2.7'
          - os: windows-latest
            platform: x64-mingw32
            ruby-version: '2.7'
          - os: windows-latest
            platform: x64-mingw-ucrt
            ruby-version: '3.1'
          - os: macos-latest
            platform: x86_64-darwin
            ruby-version: '2.7'
    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

# https://github.com/microsoft/vcpkg/issues/15931
# no good solution :(
    - name: Workaround for vcpkg
      if: startsWith(matrix.os, 'ubuntu')
      run: | 
        sudo apt-get update
        sudo apt-get install gperf

    - run: bundle exec rake gem:native:${{ matrix.platform }}

    - uses: actions/upload-artifact@v2
      with:
        name: pkg
        path: pkg/*.gem

    - name: Install gem
      run: gem install -b pkg/emf2svg-*.gem

    - name: Test conversion
      run: |
        ruby -remf2svg -e "puts File.write('output.svg', Emf2svg.from_file('spec/examples/image1.emf'), mode: 'wb')"

  cross:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: aarch64-linux
            ruby-version: '2.7'
          - os: macos-latest
            platform: arm64-darwin
            ruby-version: '2.7'
    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu gperf
        
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - run: bundle exec rake gem:native:${{ matrix.platform }}

    - uses: actions/upload-artifact@v2
      with:
        name: pkg
        path: pkg/*.gem

    - name: Install gem
      run: gem install -b pkg/emf2svg-*.gem

  publish:
    needs: [ build, cross ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true

    - uses: actions/download-artifact@v2
      with:
        name: pkg
        path: pkg

    - name: Publish to rubygems.org
      env:
        RUBYGEMS_API_KEY: ${{secrets.METANORMA_CI_RUBYGEMS_API_KEY}}
      run: |
        mkdir -p ~/.gem
        touch ~/.gem/credentials
        cat > ~/.gem/credentials << EOF
        ---
        :rubygems_api_key: ${RUBYGEMS_API_KEY}
        EOF
        chmod 0600 ~/.gem/credentials
        gem signin
        ls -l pkg/
        for gem in pkg/*.gem; do gem push -V $gem; done
